algoritmo "Registro"
// Função :
// Autor :
// Data : 14/07/2019
// Seção de Declarações
Tipo
    Cad_aluno = registro
    nome: caractere
    nota1: real
    nota2: real
    nota3: real
    nota4: real
Fimregistro
var
   aluno: cad_aluno
inicio
      Escreva ("Informe nome do aluno.: ")
      Leia (aluno.nome)
      Escreva ("Informe a nota 1.: ")
      Leia (aluno.nota1)
      Escreva ("Informe a nota 2.: ")
      Leia (aluno.nota2)
      Escreva ("Informe a nota 3.: ")
      Leia (aluno.nota3)
      Escreva ("Informe a nota 4.: ")
      Leia (aluno.nota4)
fimalgoritmo
