algoritmo "Tabuada"
// Função :
// Autor :
// Data : 08/07/2019
// Seção de Declarações 
var
   Num, i: inteiro
inicio
      Escreval ()
      Escreval ("|:XXXXXX(Tabuada)XXXXXX:|")
      Escreval ()
      Escreva ("Digite um número.: ")
      Leia (Num)
      Escreval ()
      Para i de 1 Ate 10 Passo 1 Faca
           Escreval (Num, " X", i, " =", Num * i)
      Fimpara
      Escreval ()
      Escreval ("|:XXXXXXXXXXXXXXXXXXXXX:|")
      Escreval ()
fimalgoritmo
