algoritmo "Palavra"
// Função :
// Autor :
// Data : 10/07/2019
// Seção de Declarações 
//1. Escreva um algoritmo que leia o número de vezes que se deseja imprimir a palavra
//"ALGORITMOS" e imprimir.
var
   num, i: inteiro
inicio
      Escreva ("Informe o número de vezes que deseja imprimir:")
      Leia (num)
      Para i de 1 Ate num Passo 1 Faca
           Escreval ("ALGORITMO")
      Fimpara
fimalgoritmo
