algoritmo "Funcoes"
// Função :
// Autor :
// Data : 07/07/2019
// Seção de Declarações 
//7. Elabore um algoritmo que leia um número inteiro e apresente a raiz quadrada
//e o valor deste número elevado ao quadrado.
//OBS: SQR = raizq
//OBS: SQRT = quad
var
   raiz: real
   num, quadrado: inteiro
inicio
      Escreva ("Informe um número inteiro: ")
      Leia (num)
      raiz <- raizq (num)
      quadrado <- quad (num)
      Escreval ("A raiz quadrada é: ", raiz)
      Escreval ("O número elevado ao quadrado é: ", quadrado)
fimalgoritmo
