algoritmo "Circulo"
// Função :
// Autor :
// Data : 07/07/2019
// Seção de Declarações 
//6. Escreva um algoritmo que calcule a área e o perímetro de um círculo
//OBS: SQR = raizq
var
   area, perimetro, raio: real
inicio
      Escreva ("Informe o valor do raío: ")
      Leia (raio)
      perimetro <- 2 * pi * raio
      area <- pi * (raizq(raio))
      Escreval ("A área é: ", area)
      Escreval ("O perímetro é: ", perimetro)
fimalgoritmo
