algoritmo "Cadastro"
// Função :
// Autor :
// Data : 06/07/2019
// Seção de Declarações 
var
   nome: caractere
   idade, telefone: inteiro
   peso, altura: real
inicio
      Escreva ("Informe o nome: ")
      Leia (nome)
      Escreva ("Informe a idade: ")
      Leia (idade)
      Escreva ("Informe o peso: ")
      Leia (peso)
      Escreva ("Informe a altura: ")
      Leia (altura)
      Escreva ("Informe o telefone: ")
      Leia (telefone)
      Escreval ()
      Escreval ("#########################")
      Escreval ()
      Escreval ("O nome é: ", nome)
      Escreval ("A idade é: ", idade)
      Escreval ("O peso é: ", peso)
      Escreval ("A altura é: ", altura)
      Escreval ("O telefone é: ", telefone)
      Escreval ()
      Escreval ("#########################")
      Escreval ()
fimalgoritmo
