algoritmo "Numero"
// Função :
// Autor :
// Data : 06/07/2019
// Seção de Declarações 
//1. Elabore um algoritmo que leia um número inteiro e apresente o antecessor, o número e o sucessor.
var
   num: inteiro
inicio
      Escreva ("Informe um número inteiro: ")
      Leia (num)
      Escreval ("O antecessor é: ", num - 1)
      Escreval ("O número é: ", num)
      Escreval ("O sucessor é: ", num + 1)

fimalgoritmo
