algoritmo "Triangulo"
// Função :
// Autor :
// Data : 06/07/2019
// Seção de Declarações 
//2. Escreva um algoritmo que escreva a área de um triângulo.
var
   base, altura, area: real
inicio
      Escreva ("Informe a base do triângulo: ")
      Leia (base)
      Escreva ("Informe a altura do triângulo: ")
      Leia (altura)
      area <- (base * altura) / 2
      Escreval ("A área do triângulo é: ", area)
fimalgoritmo
