algoritmo "AlgoritmoLigarIrrigação"
// Função :
// Autor :
// Data : 25/05/2019
// Seção de Declarações 
var
   umidadeSolo: inteiro
inicio
   escreva("Informe a umidade do solo")
   leia(umidadeSolo)
   se (umidadeSolo >= 50) entao
       escreva("Solo seco")
       escreva("Iniciando processo de Irrigação")
   senao
       escreva("Solo úmido")
       escreva("Encerrando processo de Irrigação")
   fimse

fimalgoritmo
