algoritmo "CadastroProduto"
// Função :
// Autor :
// Data : 09/06/2019
// Seção de Declarações
funcao cadastro(produto:caractere):caractere
       codigo: inteiro
       nome: caractere
       quantidade: inteiro
       preco: real
fimfuncao

var produto:caractere

inicio
      Escreva ("Digite o Código.:")
      Leia (produto)
      Escreva ("Digite seu Nome.:")
      Leia (produto)
      Escreva ("Digite a Quantidade.:")
      Leia (produto)
      Escreva ("Digite o preço.:")
      Leia (produto)

fimalgoritmo

