Algoritmo "DiadaSemana"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/05/2019
Var Dia:Inteiro

Inicio
      Escreva ("Informe um número que represente um dia da semana?.:")
      Leia (Dia)
      Escolha(Dia)
           Caso 1
              ESCREVA ("Domingo")
           caso 2
              ESCREVA ("Segunda-Feira")
           Caso 3
              ESCREVA ("Terça-Feira")
           Caso 4
              ESCREVA ("Quarta-Feira")
           Caso 5
              ESCREVA ("Quinta-Feira")
           Caso 6
              ESCREVA ("Sexta-Feira")
           Caso 7
              ESCREVA ("Sábado")
              Outrocaso
              Escreval ("Dia inválido")
      Fimescolha
Fimalgoritmo