Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/05/2019
Var Val,Soma:Inteiro

Inicio
      Escreva("Inície a somatória com o número ZERO.:")
      Leia(Val)
      Soma <- 0
      Enquanto (soma < 100) FACA
      Escreval (Val)
             Leia (Val)
      EscrevaL(Val+Val)
             Soma<-Soma+Val
      FIMENQUANTO

Fimalgoritmo