Algoritmo "Aguardando"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/05/2019
Var Cont: Inteiro



Inicio
      Escreva("Aperte a tecla Enter Para Iniciar")
      Leia (Cont)
      Cont<-0
      ENQUANTO(Cont <- 100) FAÇA
          Escreva("Aguarde...")
      Cont<-Cont+1
          
      FIMENQUANTO


Fimalgoritmo
