Algoritmo "Aguardando"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/05/2019
Var Cont: Inteiro



Inicio
      Escreva("Aperte a tecla Enter Para Iniciar")
      Leia (Cont)
      EscrevaL("Por gentileza aguarde em quanto o Windows está preparando a area de Trabalho")
      Para Cont de 0 ate 1000 passo 1 FAÇA
          Escreva("Aguarde...")
      FIMPARA
      
          Escreval ("Erro Faltal: Processador danificado")


Fimalgoritmo
