algoritmo "ExercicioEntradadeValorPARA"
// Função :
// Autor :
// Data : 09/06/2019
// Seção de Declarações 
var depositos: vetor[1..5] de real
          dia: inteiro
inicio
     para dia de 1 ate 5 passo 1 faca
        Escreva ("Digite valor da entrada no caixa.:")
        leia(depositos[dia])
    fimpara
    Escreval ()
    Escreval ("Vetor Estrutura Unidimencional Heterogênea")
    
    para dia de 1 ate 5 passo 1 faca
        Escreva(depositos[dia])
    fimpara

fimalgoritmo


