Algoritmo "Idade"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/05/2019
Var Idade: inteiro

Inicio
      Escreva ("Informe a idade.:")
      Leia (idade)
      Repita
          se (Idade > 18) Entao
              Escreval ("Pode jogar")
          Senao
              Escreval ("Não poderá jogar")
          Fimse
          Escreva ("Informe a idade.:")
          Leia (Idade)
      ATE (idade = 0)

Fimalgoritmo