Algoritmo "ImprimindoGuia"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/05/2019
Var Banco:Inteiro

Inicio
      Escreva ("Informe um Bamco que deseja gerar?.:")
      Leia (Banco)
      Escolha(Banco)
           Caso 1
              ESCREVA ("Sicoob Metropolitano")
           caso 2
              ESCREVA ("Sicredi Valor")
           Caso 3
              ESCREVA ("Sicredi Agro")
           Caso 4
              ESCREVA ("Sicredi União")
           Caso 5
              ESCREVA ("BBD")
           Caso 6
              ESCREVA ("CEF")
           Caso 7
              ESCREVA ("Itaú")
              Outrocaso
              Escreval ("Banco inválido")
      Fimescolha
Fimalgoritmo