Algoritmo "Nome5Vezes"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/05/2019
Var nome:caractere [30]
    i:inteiro

Inicio
      Escreva ("Digite seu nome:")
      Leia(nome)
      Para i de 1 ate 5 passo 1 Faca
          EscrevaL (Nome)
      Fimpara
      
Fimalgoritmo