Algoritmo "problema"
// Disciplina  :  [Linguagem e Lógica de Programação I]
// Professor   : Marcos Vinicius Rodrigues
// Descrição   : Recolhe dados do usuário e apresenta no fim os resultados
// Autor(a)    : Marcos
// Data atual  : 13/05/2019
Var Idade : inteiro
    Peso, altura : real
    Nome: caractere
    Telefone : caractere

Inicio
      Escreva ("Informe o nome:")
      Leia (nome)
      Escreva ("Informe a idade:")
      Leia (idade)
      Escreva ("Informe o peso:")
      Leia (peso)
      Escreva ("Informe a altura:")
      Leia (altura)
      Escreva ("Informe o telefone:")
      Leia (telefone)
      Escreval ("O nome é:", nome)
      Escreval ("A idade é:", idade)
      Escreval ("O peso é:", peso)
      Escreval ("A altura é:", altura)
      Escreval ("O telefone é:", telefone)
      
Fimalgoritmo