Algoritmo "SomaValores"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/05/2019
Var val,soma: Inteiro



Inicio
      Escreva ("Informe um número ?.:")
      soma <-0
      Enquanto (soma < 100) FAÇA
              Leia(Val)
              Soma <- Soma + Val
              Escreval(soma)
              
      FIMENQUANTO

Fimalgoritmo