Algoritmo "VetorNotas"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/05/2019
Var Notas: Vetor [1..4]de real

Inicio
      Escreva("Digite uma nota 1.:")
      Leia (Notas[1])
      Escreva("Digite uma nota 2.:")
      Leia (Notas[2])
      Escreva("Digite uma nota 3.:")
      Leia (Notas[3])
      Escreva("Digite uma nota 4.:")
      Leia (Notas[4])
      
Fimalgoritmo