algoritmo "Verificar_Idade"
// Função :
// Autor :
// Data : 07/07/2019
// Seção de Declarações
//1. Construa um algoritmo que receba o nome e a idade de uma pessoa e informe
// se é menor de idade, maior de idade ou idoso.
var
   idade: inteiro
   nome: caractere
inicio
      Escreva ("Digite o nome.: ")
      Leia (nome)
      Escreva ("Digite a idade.: ")
      Leia (idade)
      Se (idade >= 65) Entao
         Escreva ("idoso")
      Senao
      Se (Idade < 18) Entao
         Escreva ("Menor de idade")
      Senao
         Escreva ("Maior de idade")
      Fimse
      Fimse
Fimalgoritmo
