algoritmo "Mês"
// Função :
// Autor :
// Data : 07/07/2019
// Seção de Declarações 
var
   num: inteiro

inicio
      Escreva ("Digite um número de 1 a 12.: ")
      Leia (num)
      Escolha (num)
              caso 1
              Escreva ("Janeiro")
              caso 2
              Escreva ("Fevereiro")
              caso 3
              Escreva ("Março")
              caso 4
              Escreva ("Abril")
              caso 5
              Escreva ("Maio")
              caso 6
              Escreva ("Junho")
              caso 7
              Escreva ("Julho")
              caso 8
              Escreva ("Agosto")
              caso 9
              Escreva ("Setembro")
              caso 10
              Escreva ("Outubro")
              caso 11
              Escreva ("Novemro")
              caso 12
              Escreva ("Dezembro")
              outrocaso
              Escreva ("Mês inválido")
      Fimescolha
 fimalgoritmo
