algoritmo "Mês2"
// Função :
// Autor :
// Data : 07/07/2019
// Seção de Declarações 
var
   num: inteiro

inicio
      Escreva ("Digite um número de 1 a 12.: ")
      Leia (num)
      Se (num = 1) Entao
         Escreva ("Janeiro")
      Fimse
      Se (num = 2) Entao
         Escreva ("Fevereiro")
      Fimse
      Se (num = 3) Entao
         Escreva ("Março")
      Fimse
      Se (num = 4) Entao
         Escreva ("Abril")
      Fimse
      Se (num = 5) Entao
         Escreva ("Maio")
      Fimse
      Se (num = 6) Entao
         Escreva ("Junho")
      Fimse
      Se (num = 7) Entao
         Escreva ("Julho")
      Fimse
      Se (num = 8) Entao
         Escreva ("Agosto")
      Fimse
      Se (num = 9) Entao
         Escreva ("Setembro")
      Fimse
      Se (num = 10) Entao
         Escreva ("Outubro")
      Fimse
      Se (num = 11) Entao
         Escreva ("Novemro")
      Fimse
      Se (num = 12) Entao
         Escreva ("Dezembro")
      Fimse
      Se (num <> 1) e (num <> 2) e (num <> 3) e (num <> 4) e (num <> 5) e (num <> 6) e (num <> 7) e (num <> 8) e (num <> 9) e (num <> 10) e (num <> 11) e (num <> 12) Entao
         Escreva ("Mês inválido")
      Fimse
 fimalgoritmo
